Repository GY-CODING/gy-web, pull requests merged in 2024-12, with the labels that each got.

#1 feat: create mobile header and responsibe
  .gitignore
  app/components/CustomButton.tsx
  app/components/FloatingMenu.tsx
  app/components/Header.tsx
  app/components/MobileMenu.tsx
  package.json
Labels: feature

#2 fix: migrate auto-release workflow to the organization repository
  .github/workflows/auto-release.yml
  package.json
Labels: adjustement

#3 feat: First page design
  app/components/AboutSection.tsx
  app/components/Footer/Footer.tsx
  app/components/Footer/FooterLink.tsx
  app/components/Footer/SocialIcon.tsx
  app/components/Header.tsx
  app/components/LoadingScreen.tsx
  app/components/ModularSection/AnimatedGrid.tsx
  app/components/ModularSection/AnimatedIcons.tsx
  app/components/ModularSection/MobileServices.tsx
  app/components/ModularSection/ModularSection.tsx
  app/components/ModularSection/ModuleCard.tsx
  app/components/TechStack.tsx
  app/components/animations/AnimatedTitle.tsx
  app/components/animations/FadeIn.tsx
  app/components/animations/ParallaxScroll.tsx
  app/components/animations/ScaleIn.tsx
  app/components/animations/TextReveal.tsx
  app/components/lottieAnimation.tsx
  app/globals.css
  app/hooks/useScrollAnimation.ts
  app/layout.tsx
  app/metadata.ts
  app/page.tsx
  app/utils/animations.ts
  app/utils/fonts.ts
  app/utils/menuItems.ts
  app/utils/services.ts
  app/utils/styles.ts
  package-lock.json
  package.json
  public/fonts/Valorant Font.ttf
  public/icons/cloudflare.svg
  public/icons/figma.svg
  public/icons/git.svg
  public/icons/github.svg
  public/icons/gy_documents_light.svg
  public/icons/gycoding.svg
  public/icons/java.svg
  public/icons/koyeb.svg
  public/icons/linkedin.svg
  public/icons/mongodb.svg
  public/icons/nextjs.svg
  public/icons/postman.svg
  public/icons/react.svg
  public/icons/springboot.svg
  public/icons/twitter.svg
  public/icons/typescript.svg
  public/icons/unity.svg
  public/icons/vercel.svg
  public/lottie/lottie.json
  public/lottie/lottie2.json
  yarn.lock
Labels: feature

#14 Feat/product page design
  .eslintignore
  .github/workflows/auto-release
  app/components/animations/AnimatedBackground.tsx
  app/components/animations/AnimatedMesh.tsx
  app/components/animations/PixelatedBackground.tsx
  app/components/animations/RunicBackground.tsx
  app/products/[id]/components/FAQ.tsx
  app/products/[id]/components/ProductContent.tsx
  app/products/[id]/components/ProductDetails.tsx
  app/products/[id]/components/ProductFeatures.tsx
  app/products/[id]/components/SystemRequirements.tsx
  app/products/[id]/components/TechCard.tsx
  app/products/[id]/page.tsx
  app/products/data/products.ts
  app/theme.ts
  app/utils/locales.ts
  app/utils/menuItems.ts
  app/utils/productConstants.ts
  package-lock.json
  package.json
  public/images/products/heralds.webp
  yarn.lock
Labels: feature

#16 feat: Refactor product page and add technology components like respon…
  app/components/AboutSection.tsx
  app/components/animations/RunicBackground.tsx
  app/products/[id]/components/FAQ.tsx
  app/products/[id]/components/ProductContent.tsx
  app/products/[id]/components/ProductDetails.tsx
  app/products/[id]/components/ProductDetailsMobile.tsx
  app/products/[id]/components/ProductFeatures.tsx
  app/products/[id]/components/TechCard.tsx
  app/products/[id]/page.tsx
  app/utils/locales.ts
Labels: feature

#15 config: migrate release and deployment workflows
  .github/workflows/auto-release
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: adjustement, deployment
